version: "3.8"

services:
    onion-architecture-api:
        image: dotnet/onion-architecture:latest
        container_name: onion-architecture-api
        restart: always
        ports:
            - 5000:5000
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        links:
            - mariadb
        networks:
            - api
            - database
    mariadb:
        image: mariadb:10.9.2
        container_name: mariadb
        restart: always
        ports:
            - 3308:3306
        environment:
            MARIADB_ROOT_PASSWORD: 1234
        networks:
            - database
networks:
    api:
        name: api
    database:
        name: database